Reindent and clean up bin scripts

diff --git a/bin/x-terminal-emulator b/bin/x-terminal-emulator
--- a/bin/x-terminal-emulator
+++ b/bin/x-terminal-emulator
@@ -1,16 +1,15 @@
 #!/bin/sh
-# $Id$
-# -*- sh -*- vim: ft=sh sw=4 sts=4
+# vi: set et sw=2:
 
-# This script analyzes what terminal emulators are installed and picks my
-# favorite from the bunch.
+# Analyzes what terminal emulators are installed and picks my favorite from the
+# bunch.
 
 if [ -z "$DISPLAY" ]; then
-    echo "No display set.  Aborting." >&2
-    exit 2
+  echo "No display set.  Aborting." >&2
+  exit 2
 elif [ "$1" = "-E" ]; then
-    term="$2"; shift 2
-    exec "$term" "$@"
+  term="$2"; shift 2
+  exec "$term" "$@"
 fi
 
 [ -n "$XTERM" ] && [ -x "`which $XTERM 2>/dev/null`" ] && exec "$XTERM" "$@"
@@ -18,38 +17,21 @@ fi
 # NOT exported
 [ -z "$RXVT_SOCKET" ] && RXVT_SOCKET="$HOME/.rxvt-unicode-`hostname`"
 if [ -S "$RXVT_SOCKET" -a -x "`which urxvtc 2>/dev/null`" ]; then
-    urxvtc --help 2>/dev/null
-    [ "$?" = 1 ] && exec urxvtc "$@"
+  urxvtc --help 2>/dev/null
+  [ "$?" = 1 ] && exec urxvtc "$@"
 fi
 [ -x "`which urxvt 2>/dev/null`" ] && exec urxvt "$@"
-
-case "${LANG:-$LC_ALL}" in
-    *.UTF-8) ;;
-    *)
-    if [ -x "`which Eterm 2>/dev/null`" ]; then
-        if [ "x$1" = x-ut ]; then
-            shift
-            ut="--utmp-logging=false"
-        fi
-        [ "x$1" != "x+vb" -a "x$1" != "x-vb" ] || shift
-        if [ "x$1" = x-name ]; then
-            shift
-            $name="-n"
-        fi
-        exec Eterm $ut $name "$@"
-    fi ;;
-esac
 
 [ "0$LC_ALL" -eq 0 ] && LC_ALL=
 
 for dir in /opt/sfw/bin /usr/local/bin /usr/X11R6/bin; do
-    [ -x $dir/xterm ] && exec $dir/xterm "$@"
+  [ -x $dir/xterm ] && exec $dir/xterm "$@"
 done
 
 [ -x /usr/bin/xterm ] && exec /usr/bin/xterm -u8 "$@"
 
 for term in rxvt aterm konsole gnome-multi-terminal gnome-terminal dtterm; do
-    [ -x "`which $term 2>/dev/null`" ] && exec $term "$@"
+  [ -x "`which $term 2>/dev/null`" ] && exec $term "$@"
 done
 
 echo "No terminal emulators found." >&2
